name: 'GitHub Actions CSDN Email Bot'

on:
  push:
  
jobs:
  csdn-emailbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install requests
      - name: 'Working'
        run: python ./main.py
