# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: occ_seat

on:
  schedule:
    - cron: "54 5 * * *"
  

permissions:
  contents: read

jobs:
  occ_seat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python

        uses: actions/setup-python@v5
        with:
        
          python-version: '3.x'

          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
    
